src/Presentation/Sales.WebUI/Models/ErrorViewModel.cs
namespace Sales.WebUI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Presentation/Sales.WebUI/Models/MainViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Sales.WebUI.Models
{
    public class MainViewModel
    {
        [Required]
        public string Promocode { get; set; }

        /// <summary>
        /// Список всех товаров
        /// </summary>
        public IEnumerable<ProductViewModel> Products { get; set; }

        /// <summary>
        /// Корзина
        /// </summary>
        public IEnumerable<ProductViewModel> Cart { get; set; }
    }
}

src/Presentation/Sales.WebUI/Models/ProductViewModel.cs
using Sales.Core.Entity.Product;

namespace Sales.WebUI.Models
{
    public class ProductViewModel
    {
        public long Id { get; set; }

        /// <summary>
        /// Название товара
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Кол-во экземпляров
        /// </summary>
        public int CopyNumber { get; set; }

        /// <summary>
        /// Цена за единицу товара
        /// </summary>
        public decimal Price { get; set; }

        public List<ProductDetailViewModel> ProductDetails { get; set; }
    }

    public class ProductDetailViewModel
    {
        public string Attribute { get; set; }

        public string Value { get; set; }
    }
}

src/Presentation/Sales.WebUI/Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Sales.WebUI.Models
{
    public class UserViewModel
    {
        [Required]
        public string Promocode { get; set; }

        [Required]
        public string ReturnUrl { get; set; }
    }
}

src/Presentation/Sales.WebUI/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using Sales.Core.Dto;
using Sales.Core.Exceptions;
using Sales.Core.Interfaces.Clients;
using Sales.WebUI.Models;
using System.Diagnostics;

namespace Sales.WebUI.Controllers
{
    public class MainController : Controller
    {
        private readonly IProductClient _productClient;
        private readonly IOrderClient _orderClient;
        private readonly ILogger<MainController> _logger;          

        public MainController(IProductClient productClient,   
                              IOrderClient orderClient,
                              ILogger<MainController> logger)
        {            
            _productClient = productClient ?? throw new ArgumentNullException(nameof(productClient));   
            _orderClient = orderClient ?? throw new ArgumentNullException(nameof(orderClient));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public async Task<IActionResult> Index()
        {            
            string promocode = GetPromocodeFromCookie() ?? "---";

            var products = await _productClient.GetAllAsync();
            var productsViewModel = Map(products);

            //todo запросить товары из корзины
            
            return View(new MainViewModel { Promocode = promocode, Products = productsViewModel, Cart = Enumerable.Empty<ProductViewModel>() });
        }        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        /// <summary>
        /// Положить товар в корзину
        /// </summary>
        /// <param name="productId"></param>
        /// <returns></returns>
        public async Task<IActionResult> AddToCart(int productId)
        {
            try
            {
                string? promocode = GetPromocodeFromCookie();
                if (promocode != null)
                {
                    await _orderClient.AddProductToOrder(promocode, productId, quantity: 1);
                }
            }
            catch (OrderException ex)
            {
                _logger.LogError($"товар не удалось добавить в корзину. Eception: {ex}");
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteFromCart(int productId)
        {
            try
            {
                string? promocode = GetPromocodeFromCookie();
                if (promocode != null)
                {
                    await _orderClient.DeleteFromCart(promocode, productId);
                }
            }
            catch (OrderException ex)
            {
                _logger.LogError($"товар не удалось добавить в корзину. Eception: {ex}");
            }

            return RedirectToAction("Index");
        }

        public IActionResult CreateOrder()
        {
            return RedirectToAction("Index");
        }

        private string? GetPromocodeFromCookie()
        {
            var claim = HttpContext.User.Claims.FirstOrDefault(p => p.Type == "Promocode");
            if (claim != null)
            {
                return claim.Value;
            }
            else
            {
                return null;
            }
        }

        private IEnumerable<ProductViewModel> Map(IEnumerable<ProductDto> products)
        {
            var productDtos = new List<ProductViewModel>();
            foreach (ProductDto product in products)
            {
                productDtos.Add(Map(product));
            }
            return productDtos;
        }

        private ProductViewModel Map(ProductDto product)
        {
            var productDetails = new List<ProductDetailViewModel>();
            foreach (var productDetail in product.ProductDetails)
            {
                productDetails.Add(new ProductDetailViewModel
                {
                    Attribute = productDetail.Attribute,
                    Value = productDetail.Value
                });
            }
            return new ProductViewModel
            {
                Id = product.Id,
                Title = product.Title,
                CopyNumber = product.CopyNumber,
                Price = product.Price,
                ProductDetails = productDetails
            };
        }
    }
}

src/Presentation/Sales.WebUI/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Sales.Core.Interfaces.Clients;
using Sales.WebUI.Models;
using System.Security.Claims;

namespace Sales.WebUI.Controllers
{
    public class UserController : Controller
    {        
        private readonly IPromocodeClient _promocodeClient;        

        public UserController(IPromocodeClient promocodeClient)                                                               
        {
            _promocodeClient = promocodeClient ?? throw new ArgumentNullException(nameof(promocodeClient));            
        }

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Генерация промокода и аутентификация пользователя в системе
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> GeneratePromocode()
        {
            var newPromocode = await _promocodeClient.GeneratePromocodeAsync();
            return await HandleResponse(newPromocode.Value, true);            
        }

        [HttpPost]
        public async Task<IActionResult> Login(UserViewModel model)
        {      
            var promocode = await _promocodeClient.GetByPromocodeAsync(model.Promocode);            
            return await HandleResponse(model.Promocode, isSuccessStatusCode: promocode != null);            
        }

        private async Task<IActionResult> HandleResponse(string promocode, bool isSuccessStatusCode)
        {
            if (isSuccessStatusCode)
            {
                var claims = new List<Claim>
                    {
                        new Claim("Promocode", promocode)
                    };
                var claimIdentity = new ClaimsIdentity(claims, "Cookie");
                var claimPrincipal = new ClaimsPrincipal(claimIdentity);
                await HttpContext.SignInAsync("Cookie", claimPrincipal);

                return Redirect("/");
            }
            else
            {
                return Redirect("/User/Index");
            }
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }
    }
}

src/Presentation/Sales.WebUI/Views/Main/Index.cshtml
@model Sales.WebUI.Models.MainViewModel

Promocode: @Model.Promocode

<div class="text-center">    
    <form>
    <h1 class="display-4">Книги</h1>
    <table class="table">
        <tr><td>Название</td><td>Цена</td><td>Кол-во на складе</td></tr>
        @foreach (var product in @Model.Products)
        {
            <tr><td>@product.Title</td><td>@product.Price</td><td>@product.CopyNumber</td><td><button name="productId" value="@product.Id" asp-action="AddToCart">Добавить в корзину</button></td></tr>
            @foreach (var productDetail in product.ProductDetails)
            {
                <tr><td>@productDetail.Attribute - @productDetail.Value</td></tr>                
            }
                <tr><td></td></tr>
                <tr><td></td></tr>
        }
    </table>
    </form>

    <form>
    <h1 class="display-4">Корзина</h1>
        <table class="table">
            <tr><td>Название</td><td>Цена</td><td>Кол-во на складе</td></tr>
            @foreach (var product in @Model.Cart)
            {
                <tr><td>@product.Title</td><td>@product.Price</td><td>@product.CopyNumber</td><td><button name="productId" value="@product.Id" asp-action="DeleteFromCart">Удалить из корзину</button></td></tr>
                @foreach (var productDetail in product.ProductDetails)
                {
                    <tr><td>@productDetail.Attribute - @productDetail.Value</td></tr>
                }
                <tr><td></td></tr>
                <tr><td></td></tr>
            }
        </table>
        </br>
        <button asp-action="CreateOrder">Оформить заказ</button></td>
    </form>

</div>

src/Presentation/Sales.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sales.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sales.WebUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Index">Book Sale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="Index">Main</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Sales.WebUI
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Presentation/Sales.WebUI/Views/User/Index.cshtml
@model Sales.WebUI.Models.UserViewModel

<h1>Authentication</h1>

<form asp-controller="User" asp-action="GeneratePromocode" method="post">
    <button type="submit">GeneratePromocode</button>
</form>
<br></br>
<form asp-controller="User" asp-action="Login" method="post">
    <input hidden asp-for="ReturnUrl"></input>
    <div>
        <label>Promocode</label>
        <input asp-for="Promocode" />
        <span asp-validation-for="Promocode"></span>
    </div>
    <p>
        <button type="submit">Login</button>
    </p>
</form>